### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by cl886699** [liaochengcsu/Remote_Sensing_Road_Extraction#2]
你好，阅读到你的文章，想复现下结果，搭建网络的时候遇到些问题想向你请教
1、按文章中图2的结构实现的时候，我发现总参数量只有1千万出头，和文章中说的4.9千万差得比较多，不知道我漏掉了哪些细节
2、resnet50前面三层的features是取的(1, 256, 256, 64) (1, 128, 128, 256) (1, 64, 64, 512)这三个大小的吗？在256*256大小的features上做空间注意力，会占用特别多的显存，这个怎么解决呢

**Comment by liaochengcsu** [comment]
您好！感谢您关注到我们的工作，我们已在论文中公开了代码，请您参考哈~

cl886699 ***@***.***> 于2022年2月9日周三 18:11写道：

**Comment by cl886699** [comment]
> 
好的，谢谢你，我这啥眼神
